// 通用 CRUD 页面配置（驱动 CrudPage.vue）
// 字段类型: text / number / select / textarea / array(逗号分隔) / json / datetime

const CONFIRM_STATUS = ['PENDING', 'CONFIRMED', 'REJECTED']
const EFFECTIVE_STATUS = ['ENABLE', 'DISABLE']
const DATA_TYPE = ['double', 'int64', 'bool', 'string']
const EVENT_LEVEL = ['LOW', 'MEDIUM', 'HIGH']
const HANDLE_STATUS = ['UNHANDLED', 'PROCESSING', 'HANDLED']

export const pages = {
  instances: {
    title: '实例配置',
    base: '/api/timeseries/instances',
    idField: 'sequenceId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'sequenceId', label: '序列ID', type: 'text', hint: '创建时留空则由后端自动生成' },
      { name: 'instanceName', label: '实例名称', type: 'text', required: true },
      { name: 'externalSequenceId', label: '外部序列ID', type: 'text' },
      { name: 'categoryId', label: '类别ID', type: 'ref', refType: 'category', required: true, hint: '从已有类别中选择，按子串匹配过滤' },
      { name: 'deviceInstanceId', label: '设备实例ID', type: 'text' },
      { name: 'dataSourceId', label: '数据源ID', type: 'text' },
      { name: 'dataType', label: '数据类型', type: 'select', options: DATA_TYPE, required: true },
      { name: 'seriesKind', label: '序列类型', type: 'select', options: ['CONTINUOUS', 'DISCRETE', 'CATEGORICAL'] },
      { name: 'accessStatus', label: '接入状态', type: 'select', options: EFFECTIVE_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'sequenceId', label: '序列ID', type: 'ref', refType: 'instance' },
      { name: 'categoryId', label: '类别ID', type: 'ref', refType: 'category' },
      { name: 'deviceInstanceId', label: '设备实例ID', type: 'text' },
      { name: 'accessStatus', label: '接入状态', type: 'select', options: EFFECTIVE_STATUS },
    ],
    columns: [
      { key: 'sequenceId', label: '序列ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'instanceName', label: '实例名称' },
      { key: 'categoryName', label: '类别' },
      { key: 'dataType', label: '数据类型' },
      { key: 'seriesKind', label: '序列类型' },
      { key: 'accessStatus', label: '接入状态' },
      { key: 'updateTime', label: '更新时间' },
    ],
  },

  categories: {
    title: '语义类别',
    base: '/api/timeseries/semantic/categories',
    idField: 'categoryId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'categoryId', label: '类别ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'categoryName', label: '类别名称', type: 'text', required: true },
      { name: 'dataType', label: '数据类型', type: 'select', options: DATA_TYPE, required: true },
      { name: 'categoryDescription', label: '类别描述', type: 'textarea' },
      { name: 'applicableObjectType', label: '适用对象类型', type: 'text' },
      { name: 'defaultUnit', label: '默认单位', type: 'text' },
      { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'categoryId', label: '类别ID', type: 'ref', refType: 'category' },
      { name: 'keyword', label: '关键字', type: 'text' },
    ],
    statusUpdate: {
      idField: 'categoryId',
      refType: 'category',
      path: '/status',
      fields: [
        { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
        { name: 'effectiveStatus', label: '生效状态', type: 'select', options: EFFECTIVE_STATUS },
      ],
    },
    columns: [
      { key: 'categoryId', label: '类别ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'categoryName', label: '名称' },
      { key: 'dataType', label: '数据类型' },
      { key: 'defaultUnit', label: '默认单位' },
      { key: 'confirmStatus', label: '确认状态' },
    ],
  },

  constraints: {
    title: '语义约束',
    base: '/api/timeseries/semantic/constraints',
    idField: 'constraintId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'constraintId', label: '约束ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'constraintName', label: '约束名称', type: 'text', required: true },
      {
        name: 'constraintExpression',
        label: '约束表达式',
        type: 'text',
        required: true,
        placeholder: '如 x < 40',
        hint: '表达式中的变量（如 x）需在下方约束项中定义变量名并绑定映射序列',
      },
      {
        name: 'terms',
        label: '约束项 terms',
        type: 'terms',
        refType: 'instance',
        required: true,
        default: [],
        full: true,
        hint: '逐项配置变量名、映射序列、系数、采样偏移；变量映射自动生成',
      },
      { name: 'lowerBound', label: '下界', type: 'number', unit: '与序列数值同单位', hint: '留空表示无下界' },
      { name: 'upperBound', label: '上界', type: 'number', unit: '与序列数值同单位', hint: '留空表示无上界' },
      { name: 'constraintDescription', label: '约束描述', type: 'textarea' },
      { name: 'effectiveStatus', label: '生效状态', type: 'select', options: EFFECTIVE_STATUS },
      { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'constraintId', label: '约束ID', type: 'ref', refType: 'constraint' },
      { name: 'keyword', label: '关键字', type: 'text' },
    ],
    statusUpdate: {
      idField: 'constraintId',
      refType: 'constraint',
      path: '/status',
      fields: [
        { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
        { name: 'effectiveStatus', label: '生效状态', type: 'select', options: EFFECTIVE_STATUS },
      ],
    },
    columns: [
      { key: 'constraintId', label: '约束ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'constraintName', label: '名称' },
      { key: 'constraintExpression', label: '表达式' },
      { key: 'effectiveStatus', label: '生效状态' },
      { key: 'confirmStatus', label: '确认状态' },
    ],
  },

  relations: {
    title: '语义关系',
    base: '/api/timeseries/semantic/relations',
    idField: 'relationId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'relationId', label: '关系ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'relationName', label: '关系名称', type: 'text', required: true },
      { name: 'sourceSequences', label: '源序列ID', type: 'refs', refType: 'instance', required: true, full: true, hint: '从已有实例中选择，按子串匹配过滤，回车添加，可多选' },
      { name: 'targetSequenceId', label: '目标序列ID', type: 'ref', refType: 'instance', required: true, hint: '从已有实例中选择，按子串匹配过滤' },
      { name: 'relationType', label: '关系类型', type: 'select', options: ['CAUSE', 'CAUSAL', 'CORRELATION', 'ASSOCIATION'], required: true },
      { name: 'lagRange', label: '滞后范围', type: 'text', hint: '如 5 / 5m / 0m-10m（m=分钟 h=小时 d=天）' },
      { name: 'confidence', label: '置信度', type: 'number', unit: '0~1' },
      { name: 'relationDescription', label: '关系描述', type: 'textarea' },
      { name: 'effectiveStatus', label: '生效状态', type: 'select', options: EFFECTIVE_STATUS },
      { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'relationId', label: '关系ID', type: 'ref', refType: 'relation' },
      { name: 'keyword', label: '关键字', type: 'text' },
    ],
    statusUpdate: {
      idField: 'relationId',
      refType: 'relation',
      path: '/status',
      fields: [
        { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
        { name: 'effectiveStatus', label: '生效状态', type: 'select', options: EFFECTIVE_STATUS },
      ],
    },
    columns: [
      { key: 'relationId', label: '关系ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'relationName', label: '名称' },
      { key: 'sourceSequences', label: '源序列' },
      { key: 'targetSequenceId', label: '目标序列' },
      { key: 'relationType', label: '类型' },
      { key: 'confidence', label: '置信度' },
      { key: 'effectiveStatus', label: '生效状态' },
    ],
  },

  anomalyTasks: {
    title: '异常检测任务',
    base: '/api/timeseries/anomaly-tasks',
    idField: 'taskId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'taskId', label: '任务ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'taskName', label: '任务名称', type: 'text', required: true },
      { name: 'sequenceIds', label: '检测序列ID', type: 'refs', refType: 'instance', required: true, full: true, hint: '从已有实例中选择，可多选' },
      { name: 'methods', label: '检测方法（逗号分隔）', type: 'array', required: true, hint: '如 DBSCAN, ZSCORE, ISOLATION_FOREST' },
      { name: 'warningRule', label: '告警规则', type: 'text', hint: '如 anomalyLevel >= MEDIUM' },
      { name: 'contextLength', label: '上下文长度', type: 'number', unit: '点' },
      { name: 'slideStepMs', label: '滑动步长', type: 'number', unit: '毫秒' },
      { name: 'minimumPoints', label: '最小点数', type: 'number', unit: '点' },
      { name: 'constraintIds', label: '约束ID', type: 'refs', refType: 'constraint', hint: '从已有约束中选择，可多选' },
      { name: 'confirmedHistoricalEventIds', label: '已确认历史事件ID', type: 'refs', refType: 'event', hint: '从已有事件中选择，可多选' },
      { name: 'status', label: '状态', type: 'select', options: EFFECTIVE_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'taskId', label: '任务ID', type: 'ref', refType: 'anomalyTask' },
      { name: 'keyword', label: '关键字', type: 'text' },
    ],
    statusUpdate: {
      idField: 'taskId',
      refType: 'anomalyTask',
      path: '/status',
      fields: [{ name: 'status', label: '状态', type: 'select', options: EFFECTIVE_STATUS }],
    },
    columns: [
      { key: 'taskId', label: '任务ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'taskName', label: '名称' },
      { key: 'sequenceIds', label: '序列' },
      { key: 'methods', label: '方法' },
      { key: 'status', label: '状态' },
      { key: 'updateTime', label: '更新时间' },
    ],
  },

  forecastTasks: {
    title: '预测任务',
    base: '/api/timeseries/forecast-tasks',
    idField: 'taskId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'taskId', label: '任务ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'taskName', label: '任务名称', type: 'text', required: true },
      { name: 'forecastObjects', label: '预测对象', type: 'refs', refType: 'instance', required: true, full: true, hint: '从已有实例中选择，可多选' },
      { name: 'featureSequenceIds', label: '特征序列ID', type: 'refs', refType: 'instance', hint: '从已有实例中选择，可多选' },
      { name: 'forecastHorizon', label: '预测步长', type: 'text', hint: '如 24' },
      { name: 'observationWindowMs', label: '观测窗口', type: 'number', unit: '毫秒' },
      { name: 'minimumPoints', label: '最小点数', type: 'number', unit: '点' },
      { name: 'modelKey', label: '模型Key', type: 'text' },
      { name: 'constraintIds', label: '约束ID', type: 'refs', refType: 'constraint', hint: '从已有约束中选择，可多选' },
      { name: 'confirmedHistoricalEventIds', label: '已确认历史事件ID', type: 'refs', refType: 'event', hint: '从已有事件中选择，可多选' },
      { name: 'warningRule', label: '告警规则', type: 'text' },
      { name: 'status', label: '状态', type: 'select', options: EFFECTIVE_STATUS },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'taskId', label: '任务ID', type: 'ref', refType: 'forecastTask' },
      { name: 'keyword', label: '关键字', type: 'text' },
    ],
    statusUpdate: {
      idField: 'taskId',
      refType: 'forecastTask',
      path: '/status',
      fields: [{ name: 'status', label: '状态', type: 'select', options: EFFECTIVE_STATUS }],
    },
    columns: [
      { key: 'taskId', label: '任务ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'taskName', label: '名称' },
      { key: 'forecastObjects', label: '预测对象' },
      { key: 'forecastHorizon', label: '步长' },
      { key: 'modelKey', label: '模型' },
      { key: 'status', label: '状态' },
      { key: 'updateTime', label: '更新时间' },
    ],
  },

  events: {
    title: '事件管理',
    base: '/api/timeseries/events',
    idField: 'eventId',
    fields: [
      { name: 'projectId', label: '项目ID', type: 'text', placeholder: '留空 = 默认项目' },
      { name: 'eventId', label: '事件ID', type: 'text', hint: '创建时留空则自动生成' },
      { name: 'eventName', label: '事件名称', type: 'text', required: true },
      { name: 'eventType', label: '事件类型', type: 'select', options: ['ANOMALY', 'WARNING'], required: true },
      { name: 'eventSource', label: '事件来源', type: 'text', hint: '如 anomaly-detection' },
      { name: 'taskId', label: '关联任务ID', type: 'ref', refType: 'task', hint: '从已有异常/预测任务中选择' },
      { name: 'relatedSequences', label: '关联序列', type: 'refs', refType: 'instance', full: true, hint: '从已有实例中选择，可多选' },
      { name: 'relatedRules', label: '关联规则（逗号分隔）', type: 'array' },
      { name: 'eventDescription', label: '事件描述', type: 'textarea' },
      { name: 'eventLevel', label: '事件级别', type: 'select', options: EVENT_LEVEL, required: true },
      { name: 'eventTime', label: '事件时间', type: 'datetime' },
      { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
      { name: 'handleStatus', label: '处理状态', type: 'select', options: HANDLE_STATUS },
      { name: 'diagnosisResult', label: '诊断结果', type: 'text' },
      { name: 'diagnosisBasis', label: '诊断依据', type: 'textarea' },
      { name: 'disposalResult', label: '处置结果', type: 'textarea' },
      { name: 'user', label: '操作人', type: 'text' },
    ],
    queryFields: [
      { name: 'projectId', label: '项目ID', type: 'text' },
      { name: 'eventId', label: '事件ID', type: 'ref', refType: 'event' },
      { name: 'eventType', label: '事件类型', type: 'select', options: ['ANOMALY', 'WARNING'] },
      { name: 'eventSource', label: '事件来源', type: 'text' },
      { name: 'eventLevel', label: '事件级别', type: 'select', options: EVENT_LEVEL },
      { name: 'confirmStatus', label: '确认状态', type: 'select', options: CONFIRM_STATUS },
      { name: 'handleStatus', label: '处理状态', type: 'select', options: HANDLE_STATUS },
    ],
    detailGet: (row) => `/api/timeseries/events/${encodeURIComponent(row.eventId)}?projectId=${encodeURIComponent(row.projectId || '')}`,
    columns: [
      { key: 'eventId', label: '事件ID' },
      { key: 'projectId', label: '项目ID' },
      { key: 'eventName', label: '名称' },
      { key: 'eventType', label: '类型' },
      { key: 'eventLevel', label: '级别' },
      { key: 'handleStatus', label: '处理状态' },
      { key: 'eventTime', label: '事件时间' },
    ],
  },
}
